# Generated by Django 5.1 on 2024-08-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_product_is_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='is_offer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='offer_price',
        ),
    ]
